### ISSUE TITLE
Bugs with command line stuff

### ISSUE THREAD

**Issue by AlexBradley0** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#37] opened 2022-11-16 11:52 UTC
Running in spyder gives this error:
  File "c:\users\alex\ph3010\solving-tdse-for-an-arbitrary-v-x-\src\python_code\solving_tdse.py", line 257, in <module>
    TDSE.animate()

  File "c:\users\alex\ph3010\solving-tdse-for-an-arbitrary-v-x-\src\python_code\solving_tdse.py", line 226, in animate
    ani = animation.FuncAnimation(fig, self.run, TDSE.solve(self), interval=10)

TypeError: solve() takes 1 positional argument but 2 were given

I believe this may be because the command line section is calling either tdse.animate() or tdse.plot() when it should just be calling tdse(), leaving the rest of the code to sort out animate vs plot?

**Comment by AlexVernis** [comment] 2022-11-16 11:55
I ran into that same issue while troubleshooting cl before, but I can't remember exactly what caused it.

**Comment by AlexBradley0** [comment] 2022-11-16 12:06
I'm actually finding quite a lot of issues that seem to be related to the command line integration:

If I use the kwarg 'vx = "" ' to specify a potential, it now produced three separate animations, only one of which is correct and one crashes.  The first plot shows the correct one, the second is then the default and the third crashes with the same error as before.
![Capture](https://user-images.githubusercontent.com/116880130/202176017-2a833eab-6659-44d5-88c0-73e4e0626f92.PNG)

Using vx = "square" to get a square well also doesnt work correctly, not ever producing a plot/animation with a square well potential


Can you also investigate if/how these errors appear when using the command line (e.g, does it attempt to produce multiple plots still?)

**Comment by AlexVernis** [comment] 2022-11-16 12:23
<img width="865" alt="image" src="https://user-images.githubusercontent.com/116894937/202178053-c5a140dc-801d-4c22-b02c-3139a5418c88.png">
"square" works fine, no input also works fine as a test, and it doesn't attempt to print any extra images.
Issues with .plot() may be related to changing the final line in .plot() from plt.plot to plt.savefig (to output an externally readable file) - it shouldn't hurt much to just drop that back in.

Regardless, no error you've listed I have been able to reproduce through command line. It may be an issue with Spyder attempting to show all potential plots, because one of the plots you've shown is the designated default.

**Comment by dascroft** [comment] 2022-11-16 12:29
@TrueEnder, I just ran it on Visual studio and got the same results as you, could be a Spyder related issue. Regardless, it may be better to work on the README.md instructions since it will make use of the program very clear and narrow down causes of bugs etc.

**Comment by AlexVernis** [comment] 2022-11-16 12:37
Just ran probably the most recent version on Spyder with no modification and it output the default graph. Manually changed input values too, and still unable to reproduce - everything works as intended. I don't know how this happened.

**Comment by dascroft** [comment] 2022-11-16 13:09
@AlexBradley0, If the error still evident, It could be a potential issue on your end, if so I will close this issue. It can be reopened if the error persists.

**Closed as completed by dascroft** 2022-11-16 13:09 UTC
Labels: bug
